---
# Copyleft (c) 2021 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    ACMeasurement: 
      $ref: "https://smart-data-models.github.iodataModel.Energy/ACMeasurement//github/workspace/ACMeasurement/model.yaml#/ACMeasurement"
info:
  description:  |
    The Data Model intended to measure the electrical energies consumed by an electrical system which uses an Alternating Current (AC) for a three-phase (L1, L2, L3) or single-phase (L) and neutral (N). It integrates the initial version of the data Modem [THREEPHASEMEASUREMENT], extended to also perform single-phase measurements. It includes attributes for various electrical measurements such as power, frequency, current and voltage.
  title: ACMeasurement
  version: "1.0.0"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - in: query
          name: type
          required: true
          schema: 
            enum: 
              - ACMeasurement
            type: string
      responses: 
        "200": 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - $ref: "https://smart-data-models.github.io/dataModel.Energy/ACMeasurement/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - $ref: "https://smart-data-models.github.io/dataModel.Energy/ACMeasurement/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
        - ACMeasurement
tags: 
  - description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
  - description: "The Data Model intended to measure the electrical energies consumed by an electrical system which uses an Alternating Current (AC) for a three-phase (L1, L2, L3) or single-phase (L) and neutral (N). It integrates the initial version of the data Modem [THREEPHASEMEASUREMENT], extended to also perform single-phase measurements. It includes attributes for various electrical measurements such as power, frequency, current and voltage."
    name: ACMeasurement
