---
# Copyleft (c) 2021 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    PhotovoltaicDevice: 
      $ref: "https://smart-data-models.github.iodataModel.Energy/PhotovoltaicDevice//github/workspace/PhotovoltaicDevice_incubated/model.yaml#/PhotovoltaicDevice"
info:
  description:  |
    The Data Model is intended to describe the mechanical, electrical and
thermal characteristics of photo-voltaic panels according to STC - Standard
Test Condition* and *NOCT - Normal Operating Cell Temperature 
This Data Model can be used directly as a main entity to describe the
  or as a sub-entity of the Data Model  using
a reference by the attribute. The measures performed for STC and
NOCT are  (Maximum Nominal Power),  (Optimal operating voltage),
(Optimal Operating Current),  (Open Circuit Voltage), 
(Short Circuit Current).  Information about Data ModelThis
Data Model can be used directly as a main entity to describe the device
[PHOTOVOLTAIC] or as a sub-entity of the Data Model [DEVICE] using a

  title: PhotovoltaicDevice
  version: "1.0.0"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - in: query
          name: type
          required: true
          schema: 
            enum: 
              - PhotovoltaicDevice
            type: string
      responses: 
        "200": 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - $ref: "https://smart-data-models.github.io/dataModel.Energy/PhotovoltaicDevice/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - $ref: "https://smart-data-models.github.io/dataModel.Energy/PhotovoltaicDevice/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
        - PhotovoltaicDevice
tags: 
  - description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
  - description: "The Data Model is intended to describe the mechanical, electrical and
thermal characteristics of photo-voltaic panels according to STC - Standard
Test Condition* and *NOCT - Normal Operating Cell Temperature 
This Data Model can be used directly as a main entity to describe the
  or as a sub-entity of the Data Model  using
a reference by the attribute. The measures performed for STC and
NOCT are  (Maximum Nominal Power),  (Optimal operating voltage),
(Optimal Operating Current),  (Open Circuit Voltage), 
(Short Circuit Current).  Information about Data ModelThis
Data Model can be used directly as a main entity to describe the device
[PHOTOVOLTAIC] or as a sub-entity of the Data Model [DEVICE] using a
"
    name: PhotovoltaicDevice
