name: Generate swagger yaml

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*/swagger.yaml'

jobs:
  generate-yaml:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Fetch history
        run: git fetch --prune --unshallow

      - uses:  wistefan/create-openapi-yaml@master
        name: Generate swagger.yaml
        with:
          model-name: 'ACMeasurement'
          repository-name: 'dataModel.Energy'

      - uses: wistefan/create-openapi-yaml@master
        name: Generate swagger.yaml
        with:
          model-name: 'InverterDevice'
          repository-name: 'dataModel.Energy'

      - uses: wistefan/create-openapi-yaml@master
        name: Generate swagger.yaml
        with:
          model-name: 'PhotovoltaicDevice'
          repository-name: 'dataModel.Energy'
          model-folder: 'PhotovoltaicDevice_incubated'

      - uses: wistefan/create-openapi-yaml@master
        name: Generate swagger.yaml
        with:
          model-name: 'ThreePhaseAcMeasurement'
          repository-name: 'dataModel.Energy'

      - name: Configure Git
        run: |
          git config user.name '$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Generated by github-actions: Update swagger.yaml files." -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}