name: Validate schemas

on:
  push:

jobs:
  validate-schemas:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses:  wistefan/validate-data-model@master
        name: Validate ACMeasurement
        with:
          schema-file: 'ACMeasurement/schema.json'

      - uses: wistefan/validate-data-model@master
        name: Validate InverterDevice
        with:
          schema-file: 'InverterDevice/schema.json'

      - uses: wistefan/validate-data-model@master
        name: Validate PhotovoltaicDevice_incubated
        with:
          schema-file: 'PhotovoltaicDevice_incubated/schema.json'

      - uses: wistefan/validate-data-model@master
        name: Validate ThreePhaseAcMeasurement
        with:
          schema-file: 'ThreePhaseAcMeasurement/schema.json'

      - name: Annotate
        if: always()
        uses: yuzutech/annotations-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Report'
          input: '/github/workspace/annotations.json'